name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install
        working-directory: ./KanbanBoardV2

      name: Run Tests
        run: npm test -- --watch=false --no-progress --browsers=ChromeHeadlessCI
        working-directory: ./KanbanBoardV2
        env:
          CI: true

      - name: Build Angular Project
        run: npm run build --prod
        working-directory: ./KanbanBoardV2

      - name: Deploy to Firebase Hosting (Pull Request)
        if: github.event_name == 'pull_request'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KANBANBOARD_JOHN }}'
          channelId: pr-${{ github.event.pull_request.number }}
          projectId: kanbanboard-john
          expires: 7d
          entryPoint: .
          firebaseToolsVersion: latest

      - name: Deploy to Firebase Hosting (Main Branch)
        if: github.ref == 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KANBANBOARD_JOHN }}'
          channelId: live
          projectId: kanbanboard-john
          entryPoint: .
          firebaseToolsVersion: latest
